# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uv2z5T6-716RU4f9sVIH_OmG60gUd5C4
"""

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import HTML, display
from plotly.subplots import make_subplots

# --- 1. DATOS ---
np.random.seed(42)
localidades = [
    "Kennedy",
    "Suba",
    "Bosa",
    "Ciudad Bolívar",
    "Engativá",
    "Usme",
    "San Cristóbal",
    "Usaquén",
    "Fontibón",
]
sexos = ["Hombre", "Mujer"]
eventos = ["Ideación suicida", "Intento suicida", "Suicidio consumado"]

data = []
for _ in range(1200):
  data.append({
      "Localidad": np.random.choice(localidades),
      "Sexo": np.random.choice(sexos, p=[0.45, 0.55]),
      "Evento": np.random.choice(eventos, p=[0.5, 0.4, 0.1]),
      "Edad": np.random.randint(10, 85),
      "Nivel Educativo": np.random.choice(
          ["Secundaria", "Universidad", "Técnico", "Primaria", "Posgrado"]
      ),
      "Estado Civil": np.random.choice(
          ["Soltero/a", "Unión Libre", "Casado/a", "Separado/a"]
      ),
  })

df = pd.DataFrame(data)

# --- 2. ENCABEZADO HTML DESTACADO (PRIMERO QUE SE VE) ---
html_header = """
<div style="background-color: #0B0F19; padding: 25px; border-radius: 12px; text-align: center; border-bottom: 3px solid #FF007F; font-family: sans-serif; margin-bottom: 10px;">
    <h1 style="color: #00E5FF; margin: 0; font-size: 32px; letter-spacing: 1.5px; font-weight: 800; text-transform: uppercase;">
        🚨 MONITOR DE CONDUCTA SUICIDA Y SALUD MENTAL
    </h1>
    <h3 style="color: #FF007F; margin: 8px 0 0 0; font-size: 18px; font-weight: 600;">
        Observatorio de Salud Pública D.C. — Análisis Epidemiológico Bogotá
    </h3>
    <p style="color: #A0AABF; margin: 6px 0 0 0; font-size: 13px;">
        Panel de Control Interactivo | Indicadores Demográficos y Prevención
    </p>
</div>
"""
display(HTML(html_header))

# --- 3. CONFIGURACIÓN DE COLORES ---
COLOR_MUJER = "#FF007F"
COLOR_HOMBRE = "#00E5FF"
BG_COLOR = "#0B0F19"

paleta_eventos = {
    "Ideación suicida": "#FFB100",
    "Intento suicida": "#FF007F",
    "Suicidio consumado": "#9D00FF",
}

# --- 4. SUBPLOTS CON ESPACIADO CORREGIDO ---
fig = make_subplots(
    rows=3,
    cols=2,
    column_widths=[0.55, 0.45],
    row_heights=[0.18, 0.41, 0.41],
    specs=[
        [{"type": "indicator"}, {"type": "indicator"}],
        [{"type": "bar"}, {"type": "xy"}],
        [{"type": "domain"}, {"type": "bar"}],
    ],
    vertical_spacing=0.14,
    horizontal_spacing=0.10,
    subplot_titles=(
        "",
        "",
        "📍 Casos por Localidad y Sexo",
        "👥 Distribución por Edad y Tipo de Evento",
        "💍 Estado Civil",
        "🎓 Casos por Nivel Educativo",
    ),
)

# Indicador 1
fig.add_trace(
    go.Indicator(
        mode="number",
        value=len(df),
        title={"text": "<b>TOTAL CASOS REGISTRADOS</b>", "font": {"size": 13}},
        number={"font": {"color": "#00E5FF", "size": 42}},
    ),
    row=1,
    col=1,
)

# Indicador 2
fig.add_trace(
    go.Indicator(
        mode="number",
        value=int(df["Edad"].mean()),
        title={"text": "<b>PROMEDIO DE EDAD</b>", "font": {"size": 13}},
        number={"font": {"color": "#FF007F", "size": 42}, "suffix": " años"},
    ),
    row=1,
    col=2,
)

# Localidades
df_loc = df.groupby(["Localidad", "Sexo"]).size().reset_index(name="Casos")
for sexo, color in [("Hombre", COLOR_HOMBRE), ("Mujer", COLOR_MUJER)]:
  df_sub = df_loc[df_loc["Sexo"] == sexo]
  fig.add_trace(
      go.Bar(
          y=df_sub["Localidad"],
          x=df_sub["Casos"],
          name=sexo,
          orientation="h",
          marker_color=color,
          text=df_sub["Casos"],
          textposition="auto",
      ),
      row=2,
      col=1,
  )

# Edad y Evento
for evento, color in paleta_eventos.items():
  df_ev = df[df["Evento"] == evento]
  fig.add_trace(
      go.Histogram(
          x=df_ev["Edad"],
          name=evento,
          marker_color=color,
          opacity=0.75,
          nbinsx=15,
      ),
      row=2,
      col=2,
  )

# Estado Civil
df_civil = df["Estado Civil"].value_counts().reset_index()
df_civil.columns = ["Estado", "Cantidad"]
fig.add_trace(
    go.Pie(
        labels=df_civil["Estado"],
        values=df_civil["Cantidad"],
        hole=0.5,
        marker_colors=["#00E5FF", "#FF007F", "#FFB100", "#9D00FF"],
        textinfo="label+percent",
        showlegend=False,
    ),
    row=3,
    col=1,
)

# Nivel Educativo
df_edu = df.groupby(["Nivel Educativo", "Sexo"]).size().reset_index(name="Casos")
for sexo, color in [("Hombre", COLOR_HOMBRE), ("Mujer", COLOR_MUJER)]:
  df_sub = df_edu[df_edu["Sexo"] == sexo]
  fig.add_trace(
      go.Bar(
          x=df_sub["Nivel Educativo"],
          y=df_sub["Casos"],
          name=f"{sexo} (Edu)",
          marker_color=color,
          showlegend=False,
      ),
      row=3,
      col=2,
  )

# --- 5. AJUSTES DE MARGEN Y LEYENDA (DESPEJADO) ---
fig.update_layout(
    template="plotly_dark",
    paper_bgcolor=BG_COLOR,
    plot_bgcolor=BG_COLOR,
    height=950,
    barmode="group",
    margin=dict(l=40, r=40, t=40, b=80),  # Margen superior reducido y amplio abajo
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.08,  # Mueve la leyenda abajo de todo el gráfico
        xanchor="center",
        x=0.5,
        font=dict(size=12),
    ),
)

fig.update_xaxes(showgrid=True, gridcolor="#1E293B")
fig.update_yaxes(showgrid=True, gridcolor="#1E293B")

fig.show()